
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/node_modules/ace/lib/ s3://wakari-static/apps/c9/ace/lib/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/node_modules/ace/build/src/ s3://wakari-static/apps/c9/ace/build/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/plugins-client/lib.ace/www/ s3://wakari-static/apps/c9/ace/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/plugins-client/lib.apf/www/ s3://wakari-static/apps/c9/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/node_modules/treehugger/lib/ s3://wakari-static/apps/c9/treehugger/lib/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/node_modules/v8debug/lib/ s3://wakari-static/apps/c9/v8debug/lib/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/plugins-client/lib.requirejs/www/ s3://wakari-static/apps/c9/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/node_modules/engine.io-client/ s3://wakari-static/apps/c9/engine.io/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/plugins-server/c9.smith.io/www/ s3://wakari-static/apps/c9/smith.io/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/node_modules/smith/ s3://wakari-static/apps/c9/smith/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/node_modules/msgpack-js-browser/ s3://wakari-static/apps/c9/msgpack-js/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.anims/ s3://wakari-static/apps/c9/ext/anims/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.autosave/ s3://wakari-static/apps/c9/ext/autosave/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.autotest/ s3://wakari-static/apps/c9/ext/autotest/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.beautify/ s3://wakari-static/apps/c9/ext/beautify/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.clipboard/ s3://wakari-static/apps/c9/ext/clipboard/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.closeconfirmation/ s3://wakari-static/apps/c9/ext/closeconfirmation/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.code/ s3://wakari-static/apps/c9/ext/code/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.codecomplete/ s3://wakari-static/apps/c9/ext/codecomplete/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.codetools/ s3://wakari-static/apps/c9/ext/codetools/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.colorpicker/ s3://wakari-static/apps/c9/ext/colorpicker/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.commands/ s3://wakari-static/apps/c9/ext/commands/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.connect/ s3://wakari-static/apps/c9/ext/connect/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.console/ s3://wakari-static/apps/c9/ext/console/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.consolehints/ s3://wakari-static/apps/c9/ext/consolehints/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.csslanguage/ s3://wakari-static/apps/c9/ext/csslanguage/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.dbg-node/ s3://wakari-static/apps/c9/ext/dbg-node/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.debugger/ s3://wakari-static/apps/c9/ext/debugger/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.dockpanel/ s3://wakari-static/apps/c9/ext/dockpanel/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.docs/ s3://wakari-static/apps/c9/ext/docs/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.dragdrop/ s3://wakari-static/apps/c9/ext/dragdrop/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.editors/ s3://wakari-static/apps/c9/ext/editors/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.extmgr/ s3://wakari-static/apps/c9/ext/extmgr/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.filelist/ s3://wakari-static/apps/c9/ext/filelist/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.filesystem/ s3://wakari-static/apps/c9/ext/filesystem/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.formatjson/ s3://wakari-static/apps/c9/ext/formatjson/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.ftp/ s3://wakari-static/apps/c9/ext/ftp/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.gitblame/ s3://wakari-static/apps/c9/ext/gitblame/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.githistory/ s3://wakari-static/apps/c9/ext/githistory/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.gittools/ s3://wakari-static/apps/c9/ext/gittools/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.gotofile/ s3://wakari-static/apps/c9/ext/gotofile/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.gotoline/ s3://wakari-static/apps/c9/ext/gotoline/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.guidedtour/ s3://wakari-static/apps/c9/ext/guidedtour/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.helloworld/ s3://wakari-static/apps/c9/ext/helloworld/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.help/ s3://wakari-static/apps/c9/ext/help/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.htmllanguage/ s3://wakari-static/apps/c9/ext/htmllanguage/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.imgview/ s3://wakari-static/apps/c9/ext/imgview/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.jslanguage/ s3://wakari-static/apps/c9/ext/jslanguage/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.keybindings_default/ s3://wakari-static/apps/c9/ext/keybindings_default/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.language/ s3://wakari-static/apps/c9/ext/language/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.linereport/ s3://wakari-static/apps/c9/ext/linereport/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.linereport_php/ s3://wakari-static/apps/c9/ext/linereport_php/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.linereport_python/ s3://wakari-static/apps/c9/ext/linereport_python/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.log/ s3://wakari-static/apps/c9/ext/log/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.main/ s3://wakari-static/apps/c9/ext/main/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.menus/ s3://wakari-static/apps/c9/ext/menus/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.minimap/ s3://wakari-static/apps/c9/ext/minimap/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.newresource/ s3://wakari-static/apps/c9/ext/newresource/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.noderunner/ s3://wakari-static/apps/c9/ext/noderunner/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.nodeunit/ s3://wakari-static/apps/c9/ext/nodeunit/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.offline/ s3://wakari-static/apps/c9/ext/offline/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.openfiles/ s3://wakari-static/apps/c9/ext/openfiles/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.panels/ s3://wakari-static/apps/c9/ext/panels/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.preview/ s3://wakari-static/apps/c9/ext/preview/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.quickstart/ s3://wakari-static/apps/c9/ext/quickstart/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.quickwatch/ s3://wakari-static/apps/c9/ext/quickwatch/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.recentfiles/ s3://wakari-static/apps/c9/ext/recentfiles/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.remotecontrol/ s3://wakari-static/apps/c9/ext/remotecontrol/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.revisions/ s3://wakari-static/apps/c9/ext/revisions/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.richtext/ s3://wakari-static/apps/c9/ext/richtext/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.run/ s3://wakari-static/apps/c9/ext/run/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.runpanel/ s3://wakari-static/apps/c9/ext/runpanel/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.save/ s3://wakari-static/apps/c9/ext/save/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.searchinfiles/ s3://wakari-static/apps/c9/ext/searchinfiles/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.searchreplace/ s3://wakari-static/apps/c9/ext/searchreplace/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.settings/ s3://wakari-static/apps/c9/ext/settings/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.sidebar/ s3://wakari-static/apps/c9/ext/sidebar/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.splitview/ s3://wakari-static/apps/c9/ext/splitview/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.statusbar/ s3://wakari-static/apps/c9/ext/statusbar/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.stripws/ s3://wakari-static/apps/c9/ext/stripws/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.tabbehaviors/ s3://wakari-static/apps/c9/ext/tabbehaviors/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.tabsessions/ s3://wakari-static/apps/c9/ext/tabsessions/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.testpanel/ s3://wakari-static/apps/c9/ext/testpanel/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.themes/ s3://wakari-static/apps/c9/ext/themes/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.themes_default/ s3://wakari-static/apps/c9/ext/themes_default/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.tooltip/ s3://wakari-static/apps/c9/ext/tooltip/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.tree/ s3://wakari-static/apps/c9/ext/tree/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.undo/ s3://wakari-static/apps/c9/ext/undo/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.uploadfiles/ s3://wakari-static/apps/c9/ext/uploadfiles/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.vim/ s3://wakari-static/apps/c9/ext/vim/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.watcher/ s3://wakari-static/apps/c9/ext/watcher/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/configs/../plugins-client/ext.zen/ s3://wakari-static/apps/c9/ext/zen/
s3cmd sync  --recursive /Users/sean/Documents/wakari/cloud9/plugins-client/cloud9.core/www/ s3://wakari-static/apps/c9/
